version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "get-xmltojson-data"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-17kz980dd59l2"
s3_prefix = "get-xmltojson-data"
region = "ap-south-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []