AWSTemplateFormatVersion: 2010-09-09
Description: >-
  get XML Data from http://restapi.adequateshop.com/api/Traveler then convert them to json and store it in to S3 bucket. 
Transform:
- AWS::Serverless-2016-10-31
Resources:
  getXMLDataAndStoreToS3Function:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/get-store-xml-data.getXMLDataAndStoreToS3Handler
      Runtime: nodejs14.x
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 100
      Description: get XML Data from http://restapi.adequateshop.com/api/Traveler then convert them to json and store it in to s3 bucket and send json.
      Events:
        Api:
          Type: Api
          Properties:
            Path: /
            Method: GET
Outputs:
  WebEndpoint:
    Description: "API Gateway endpoint URL for Prod stage"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
